### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by NathanSalapat** [LandonAConway/online_shop#1]
The mod is called online_shopping, but internally you are using online_shop. Renaming the directory to online_shop doesn't seem to fix the issue either.

**Comment by LandonAConway** [comment]
Can you quote the error that shows in minetest on load?

**Comment by LandonAConway** [comment]
> The mod is called online_shopping, but internally you are using online_shop. Renaming the directory to online_shop doesn't seem to fix the issue either.

Can you quote the entire error message that you get when it does not work while it is named "online_shop"?

**Comment by NathanSalapat** [comment]
Hmmm, looks like it may have been an error on my end, as I tried again and it worked this time. Though when I placed a shop and put some text into the text box and clicked 'Finish' I got this error.
```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'online_shop' in callback on_playerReceiveFields(): /home/nathan/.minetest/mods/online_shop/shop.lua:121: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
	[C]: in function 'find'
	/home/nathan/.minetest/mods/online_shop/shop.lua:121: in function '?'
	...ome/nathan/Minetest/bin/../builtin/game/register.lua:429: in function <...ome/nathan/Minetest/bin/../builtin/game/register.lua:413>```

**Comment by LandonAConway** [comment]
> Hmmm, looks like it may have been an error on my end, as I tried again and it worked this time. Though when I placed a shop and put some text into the text box and clicked 'Finish' I got this error.
> 
> ```
> AsyncErr: ServerThread::run Lua: Runtime error from mod 'online_shop' in callback on_playerReceiveFields(): /home/nathan/.minetest/mods/online_shop/shop.lua:121: bad argument #1 to 'find' (string expected, got nil)
> stack traceback:
> 	[C]: in function 'find'
> 	/home/nathan/.minetest/mods/online_shop/shop.lua:121: in function '?'
> 	...ome/nathan/Minetest/bin/../builtin/game/register.lua:429: in function <...ome/nathan/Minetest/bin/../builtin/game/register.lua:413>```
> ```

That's very very odd. I downloaded and ran what I uploaded to GitHub and it works just fine for me. Which version of Minetest are you running. You need 5.1.1 or greater.

**Comment by LandonAConway** [comment]
The issue was that it was not checking if a field was null before continuing. The next time this happens you will get an "operation failed" in the chat console instead of a game crash. Make sure you fully type in a shop name and etc otherwise you will be sent that message in-game. And make sure your store name and item label does not contain the "|" character. The game will not crash anymore though.
