### ISSUE TITLE
Can't save a shop

### ISSUE THREAD

**Issue by NathanSalapat** [LandonAConway/online_shop#2]
I keep getting this error when opening the shop formspec by right clicking on a shop node.
`2020-05-10 10:13:21: ERROR[Main]: Invalid field element(6): '0.3,5.548;4,1;store_name;Store Name:;;'`

When I click the Finish button I get this message in chat;
`Operation failed. Enter a valid 'Store Name' and 'Item Label'`
There is only one box to enter text into, and no instructions on what the separator should be, if it's using one.
When I try to run /online_shopping it just says there are no shops, likely because of the error when I try to save the shop.

**Comment by LandonAConway** [comment]
The last thing is on purpose. Other people have ran this mod without problems so I don't know why you are. I will still try to fix the problem but, what version of minetest are you running?

**Comment by LandonAConway** [comment]
It should work now. Let me know.

**Comment by NathanSalapat** [comment]
Working now. Using the latest dev build, compiled this morning at 4am my time.
