### ISSUE TITLE
Online Shop Not Working With Minetest 5.3.0

### ISSUE THREAD

**Issue by AccreditedDesign** [LandonAConway/online_shop#4]
Just updated to Minetest 5.3.0 and enabled this mod. I get the error:
"Failed to enable mod "online_shop-master" as it contains disallowed characters. Only characters [a-z0-9_] are allowed."

**Comment by LandonAConway** [comment]
Sorry for the late comment. This problem occurs becuase you need to remove "-master" from the name of the mod's folder.
